services:
  - type: web
    name: krishimitra
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENWEATHERMAP_API_KEY
        sync: false
      - key: gemini-api
        sync: false
      - key: SESSION_SECRET
        generateValue: true 